"""Tests for the versioned invocation-identity primitive (engine/invocation.py).

Golden hash vectors were independently precomputed (Python `json.dumps` with
the same canonicalization contract as `engine/canonical.py`, cross-checked
with the system `sha256sum` binary) before being hard-coded here -- never
generated by calling `engine.invocation` itself.
"""

import copy
import math
import unittest
from dataclasses import FrozenInstanceError

from engine.canonical import canonical_json, sha256_hash
from engine.invocation import (
    INVOCATION_FORMAT,
    MODE_SYNC_NON_STREAMING,
    MODE_SYNC_STREAMING,
    SURFACE_ANTHROPIC_MESSAGES,
    SURFACE_LITELLM_COMPLETION,
    SURFACE_OPENAI_CHAT_COMPLETIONS,
    InvocationIdentity,
    InvocationIdentityError,
    build_invocation_identity,
    parse_invocation_identity,
)

# --- golden vector (independently precomputed, see module docstring) ------

_GOLDEN_SURFACE = SURFACE_ANTHROPIC_MESSAGES
_GOLDEN_MODE = MODE_SYNC_NON_STREAMING
_GOLDEN_MODEL = "claude-3-5-sonnet-20241022"
_GOLDEN_MESSAGES = [{"role": "user", "content": "hello"}]
_GOLDEN_PARAMETERS = {"max_tokens": 1024}
_GOLDEN_HASH = (
    "0ea189eb5ec49364fe33a5fd01de1b650537c0952cab0c8efe938d829ea15dce"
)


def _build(**overrides):
    kwargs = dict(
        surface=SURFACE_LITELLM_COMPLETION,
        mode=MODE_SYNC_NON_STREAMING,
        model="openai/gpt-4o",
        messages=[{"role": "user", "content": "hi"}],
        parameters=None,
    )
    kwargs.update(overrides)
    return build_invocation_identity(**kwargs)


class TestConstruction(unittest.TestCase):
    def test_valid_openai_non_streaming(self):
        identity = build_invocation_identity(
            surface=SURFACE_OPENAI_CHAT_COMPLETIONS,
            mode=MODE_SYNC_NON_STREAMING,
            model="gpt-4o",
            messages=[{"role": "user", "content": "hi"}],
        )
        self.assertEqual(identity.format, INVOCATION_FORMAT)
        self.assertEqual(identity.surface, SURFACE_OPENAI_CHAT_COMPLETIONS)
        self.assertEqual(identity.mode, MODE_SYNC_NON_STREAMING)
        self.assertEqual(len(identity.hash_sha256), 64)

    def test_valid_openai_streaming(self):
        identity = build_invocation_identity(
            surface=SURFACE_OPENAI_CHAT_COMPLETIONS,
            mode=MODE_SYNC_STREAMING,
            model="gpt-4o",
            messages=[{"role": "user", "content": "hi"}],
        )
        self.assertEqual(identity.mode, MODE_SYNC_STREAMING)

    def test_valid_anthropic_with_max_tokens(self):
        identity = build_invocation_identity(
            surface=SURFACE_ANTHROPIC_MESSAGES,
            mode=MODE_SYNC_NON_STREAMING,
            model=_GOLDEN_MODEL,
            messages=_GOLDEN_MESSAGES,
            parameters={"max_tokens": 1024},
        )
        self.assertEqual(
            identity.to_stored_object()["request"]["parameters"],
            {"max_tokens": 1024},
        )

    def test_valid_litellm_with_allowed_parameters(self):
        identity = build_invocation_identity(
            surface=SURFACE_LITELLM_COMPLETION,
            mode=MODE_SYNC_NON_STREAMING,
            model="openai/gpt-4o",
            messages=[{"role": "user", "content": "hi"}],
            parameters={
                "temperature": 0.0,
                "max_tokens": 128,
                "top_p": 1.0,
                "seed": 42,
                "stop": ["\n"],
            },
        )
        self.assertEqual(len(identity.hash_sha256), 64)


class TestDeterminism(unittest.TestCase):
    def test_same_semantic_input_same_hash(self):
        a = _build()
        b = _build()
        self.assertEqual(a.hash_sha256, b.hash_sha256)

    def test_object_key_ordering_does_not_affect_hash(self):
        a = _build(messages=[{"role": "user", "content": "hi"}])
        b = _build(messages=[{"content": "hi", "role": "user"}])
        self.assertEqual(a.hash_sha256, b.hash_sha256)

    def test_array_ordering_does_affect_hash(self):
        msg_a = {"role": "user", "content": "first"}
        msg_b = {"role": "assistant", "content": "second"}
        a = _build(messages=[msg_a, msg_b])
        b = _build(messages=[msg_b, msg_a])
        self.assertNotEqual(a.hash_sha256, b.hash_sha256)

    def test_lowercase_64_hex_hash(self):
        identity = _build()
        self.assertRegex(identity.hash_sha256, r"^[0-9a-f]{64}$")

    def test_golden_vector(self):
        identity = build_invocation_identity(
            surface=_GOLDEN_SURFACE,
            mode=_GOLDEN_MODE,
            model=_GOLDEN_MODEL,
            messages=_GOLDEN_MESSAGES,
            parameters=_GOLDEN_PARAMETERS,
        )
        self.assertEqual(identity.hash_sha256, _GOLDEN_HASH)


class TestDomainSeparation(unittest.TestCase):
    def test_same_request_different_surface_different_hash(self):
        a = build_invocation_identity(
            surface=SURFACE_ANTHROPIC_MESSAGES,
            mode=MODE_SYNC_NON_STREAMING,
            model="shared-model",
            messages=[{"role": "user", "content": "hi"}],
        )
        b = build_invocation_identity(
            surface=SURFACE_LITELLM_COMPLETION,
            mode=MODE_SYNC_NON_STREAMING,
            model="shared-model",
            messages=[{"role": "user", "content": "hi"}],
        )
        self.assertNotEqual(a.hash_sha256, b.hash_sha256)

    def test_openai_streaming_vs_non_streaming_different_hash(self):
        common = dict(
            surface=SURFACE_OPENAI_CHAT_COMPLETIONS,
            model="gpt-4o",
            messages=[{"role": "user", "content": "hi"}],
        )
        a = build_invocation_identity(mode=MODE_SYNC_NON_STREAMING, **common)
        b = build_invocation_identity(mode=MODE_SYNC_STREAMING, **common)
        self.assertNotEqual(a.hash_sha256, b.hash_sha256)

    def test_format_participates_in_hash_isolated_construction(self):
        request = {"model": "shared-model", "messages": [{"role": "user", "content": "hi"}]}
        v1_material = {
            "format": INVOCATION_FORMAT,
            "surface": SURFACE_ANTHROPIC_MESSAGES,
            "mode": MODE_SYNC_NON_STREAMING,
            "request": request,
        }
        other_material = {**v1_material, "format": "aelitium-invocation-v2"}

        v1_hash = sha256_hash(canonical_json(v1_material))
        other_hash = sha256_hash(canonical_json(other_material))
        self.assertNotEqual(v1_hash, other_hash)

        identity = build_invocation_identity(
            surface=SURFACE_ANTHROPIC_MESSAGES,
            mode=MODE_SYNC_NON_STREAMING,
            model="shared-model",
            messages=[{"role": "user", "content": "hi"}],
        )
        self.assertEqual(identity.hash_sha256, v1_hash)

    def test_parser_rejects_unknown_format(self):
        identity = _build()
        stored = identity.to_stored_object()
        stored["format"] = "aelitium-invocation-v2"
        with self.assertRaises(InvocationIdentityError) as ctx:
            parse_invocation_identity(stored)
        self.assertEqual(ctx.exception.reason, "INVOCATION_BAD_FORMAT")


class TestBehaviorParameters(unittest.TestCase):
    def test_anthropic_max_tokens_changes_hash(self):
        common = dict(
            surface=SURFACE_ANTHROPIC_MESSAGES,
            mode=MODE_SYNC_NON_STREAMING,
            model=_GOLDEN_MODEL,
            messages=_GOLDEN_MESSAGES,
        )
        a = build_invocation_identity(parameters={"max_tokens": 128}, **common)
        b = build_invocation_identity(parameters={"max_tokens": 4096}, **common)
        self.assertNotEqual(a.hash_sha256, b.hash_sha256)

    def test_litellm_temperature_changes_hash(self):
        a = _build(parameters={"temperature": 0.0})
        b = _build(parameters={"temperature": 1.0})
        self.assertNotEqual(a.hash_sha256, b.hash_sha256)

    def test_litellm_max_tokens_changes_hash(self):
        a = _build(parameters={"max_tokens": 128})
        b = _build(parameters={"max_tokens": 4096})
        self.assertNotEqual(a.hash_sha256, b.hash_sha256)

    def test_litellm_top_p_changes_hash(self):
        a = _build(parameters={"top_p": 0.1})
        b = _build(parameters={"top_p": 0.9})
        self.assertNotEqual(a.hash_sha256, b.hash_sha256)

    def test_litellm_seed_changes_hash(self):
        a = _build(parameters={"seed": 1})
        b = _build(parameters={"seed": 2})
        self.assertNotEqual(a.hash_sha256, b.hash_sha256)

    def test_litellm_stop_changes_hash(self):
        a = _build(parameters={"stop": ["\n"]})
        b = _build(parameters={"stop": ["END"]})
        self.assertNotEqual(a.hash_sha256, b.hash_sha256)


class TestPresence(unittest.TestCase):
    def test_omitted_vs_explicit_null_different_hash(self):
        omitted = _build(parameters=None)
        explicit_null = _build(parameters={"temperature": None})
        self.assertNotEqual(omitted.hash_sha256, explicit_null.hash_sha256)

    def test_empty_parameters_dict_same_as_omitted(self):
        omitted = _build(parameters=None)
        empty = _build(parameters={})
        self.assertEqual(omitted.hash_sha256, empty.hash_sha256)


class TestStrictness(unittest.TestCase):
    def test_unsupported_surface_rejected(self):
        with self.assertRaises(InvocationIdentityError) as ctx:
            _build(surface="cohere.chat")
        self.assertEqual(ctx.exception.reason, "INVOCATION_BAD_SURFACE")

    def test_unsupported_mode_rejected(self):
        with self.assertRaises(InvocationIdentityError) as ctx:
            _build(mode="async_streaming")
        self.assertEqual(ctx.exception.reason, "INVOCATION_BAD_MODE")

    def test_invalid_surface_mode_combination_rejected(self):
        with self.assertRaises(InvocationIdentityError) as ctx:
            build_invocation_identity(
                surface=SURFACE_ANTHROPIC_MESSAGES,
                mode=MODE_SYNC_STREAMING,
                model=_GOLDEN_MODEL,
                messages=_GOLDEN_MESSAGES,
            )
        self.assertEqual(ctx.exception.reason, "INVOCATION_BAD_MODE")

    def test_unknown_top_level_field_rejected(self):
        stored = _build().to_stored_object()
        stored["extra_field"] = "unexpected"
        with self.assertRaises(InvocationIdentityError) as ctx:
            parse_invocation_identity(stored)
        self.assertEqual(ctx.exception.reason, "INVOCATION_BAD_STRUCTURE")

    def test_missing_top_level_field_rejected(self):
        stored = _build().to_stored_object()
        del stored["mode"]
        with self.assertRaises(InvocationIdentityError) as ctx:
            parse_invocation_identity(stored)
        self.assertEqual(ctx.exception.reason, "INVOCATION_BAD_STRUCTURE")

    def test_null_messages_rejected(self):
        with self.assertRaises(InvocationIdentityError) as ctx:
            build_invocation_identity(
                surface=SURFACE_OPENAI_CHAT_COMPLETIONS,
                mode=MODE_SYNC_NON_STREAMING,
                model="gpt-4o",
                messages=None,
            )
        self.assertEqual(ctx.exception.reason, "INVOCATION_BAD_REQUEST")

    def test_missing_required_request_field_rejected(self):
        stored = _build().to_stored_object()
        del stored["request"]["messages"]
        with self.assertRaises(InvocationIdentityError) as ctx:
            parse_invocation_identity(stored)
        self.assertEqual(ctx.exception.reason, "INVOCATION_BAD_REQUEST")
        self.assertIn("missing required field", ctx.exception.detail)

    def test_unknown_request_field_rejected(self):
        stored = _build().to_stored_object()
        stored["request"]["unexpected"] = "value"
        with self.assertRaises(InvocationIdentityError) as ctx:
            parse_invocation_identity(stored)
        self.assertEqual(ctx.exception.reason, "INVOCATION_BAD_REQUEST")

    def test_unknown_parameter_for_surface_rejected(self):
        with self.assertRaises(InvocationIdentityError) as ctx:
            build_invocation_identity(
                surface=SURFACE_ANTHROPIC_MESSAGES,
                mode=MODE_SYNC_NON_STREAMING,
                model=_GOLDEN_MODEL,
                messages=_GOLDEN_MESSAGES,
                parameters={"temperature": 0.5},
            )
        self.assertEqual(ctx.exception.reason, "INVOCATION_BAD_PARAMETER")

    def test_non_string_model_rejected(self):
        with self.assertRaises(InvocationIdentityError) as ctx:
            _build(model=12345)
        self.assertEqual(ctx.exception.reason, "INVOCATION_BAD_REQUEST")

    def test_empty_model_rejected(self):
        with self.assertRaises(InvocationIdentityError) as ctx:
            _build(model="")
        self.assertEqual(ctx.exception.reason, "INVOCATION_BAD_REQUEST")

    def test_messages_not_list_rejected(self):
        with self.assertRaises(InvocationIdentityError) as ctx:
            _build(messages={"role": "user", "content": "hi"})
        self.assertEqual(ctx.exception.reason, "INVOCATION_BAD_REQUEST")

    def test_non_string_dict_key_rejected(self):
        with self.assertRaises(InvocationIdentityError) as ctx:
            _build(messages=[{1: "value"}])
        self.assertEqual(ctx.exception.reason, "INVOCATION_BAD_VALUE")

    def test_bytes_rejected(self):
        with self.assertRaises(InvocationIdentityError) as ctx:
            _build(messages=[{"role": "user", "content": b"raw bytes"}])
        self.assertEqual(ctx.exception.reason, "INVOCATION_BAD_VALUE")

    def test_set_rejected(self):
        with self.assertRaises(InvocationIdentityError) as ctx:
            _build(messages=[{"role": "user", "content": {1, 2, 3}}])
        self.assertEqual(ctx.exception.reason, "INVOCATION_BAD_VALUE")

    def test_nan_rejected(self):
        with self.assertRaises(InvocationIdentityError) as ctx:
            _build(parameters={"temperature": math.nan})
        self.assertEqual(ctx.exception.reason, "INVOCATION_BAD_VALUE")

    def test_positive_infinity_rejected(self):
        with self.assertRaises(InvocationIdentityError) as ctx:
            _build(parameters={"temperature": math.inf})
        self.assertEqual(ctx.exception.reason, "INVOCATION_BAD_VALUE")

    def test_negative_infinity_rejected(self):
        with self.assertRaises(InvocationIdentityError) as ctx:
            _build(parameters={"temperature": -math.inf})
        self.assertEqual(ctx.exception.reason, "INVOCATION_BAD_VALUE")

    def test_tuple_rejected(self):
        with self.assertRaises(InvocationIdentityError) as ctx:
            _build(messages=({"role": "user", "content": "hi"},))
        self.assertEqual(ctx.exception.reason, "INVOCATION_BAD_REQUEST")


class TestHashVerification(unittest.TestCase):
    def test_stored_valid_hash_accepted(self):
        identity = _build()
        stored = identity.to_stored_object()
        reparsed = parse_invocation_identity(stored)
        self.assertEqual(reparsed.hash_sha256, identity.hash_sha256)

    def test_malformed_stored_hash_rejected(self):
        stored = _build().to_stored_object()
        stored["hash_sha256"] = "not-a-valid-hash"
        with self.assertRaises(InvocationIdentityError) as ctx:
            parse_invocation_identity(stored)
        self.assertEqual(ctx.exception.reason, "INVOCATION_BAD_HASH")

    def test_uppercase_stored_hash_rejected(self):
        stored = _build().to_stored_object()
        stored["hash_sha256"] = stored["hash_sha256"].upper()
        with self.assertRaises(InvocationIdentityError) as ctx:
            parse_invocation_identity(stored)
        self.assertEqual(ctx.exception.reason, "INVOCATION_BAD_HASH")

    def test_wrong_but_well_formed_hash_mismatch(self):
        stored = _build().to_stored_object()
        stored["hash_sha256"] = "0" * 64
        with self.assertRaises(InvocationIdentityError) as ctx:
            parse_invocation_identity(stored)
        self.assertEqual(ctx.exception.reason, "INVOCATION_HASH_MISMATCH")

    def test_changed_request_without_updated_hash_mismatch(self):
        stored = _build().to_stored_object()
        stored["request"]["model"] = "a-different-model"
        with self.assertRaises(InvocationIdentityError) as ctx:
            parse_invocation_identity(stored)
        self.assertEqual(ctx.exception.reason, "INVOCATION_HASH_MISMATCH")


class TestImmutability(unittest.TestCase):
    def test_frozen_dataclass_rejects_attribute_assignment(self):
        identity = _build()
        with self.assertRaises(FrozenInstanceError):
            identity.hash_sha256 = "tampered"

    def test_mutating_stored_object_does_not_affect_identity(self):
        identity = _build()
        stored = identity.to_stored_object()
        original_hash = identity.hash_sha256
        stored["request"]["model"] = "tampered-model"
        stored["hash_sha256"] = "tampered-hash"
        self.assertEqual(identity.hash_sha256, original_hash)
        self.assertEqual(
            identity.to_stored_object()["request"]["model"],
            "openai/gpt-4o",
        )


class TestRoundTrip(unittest.TestCase):
    def test_build_then_parse_matches(self):
        built = _build(parameters={"temperature": 0.2, "max_tokens": 64})
        reparsed = parse_invocation_identity(built.to_stored_object())
        self.assertEqual(built.hash_sha256, reparsed.hash_sha256)
        self.assertEqual(built.to_stored_object(), reparsed.to_stored_object())

    def test_deepcopy_of_stored_object_is_independent(self):
        built = _build()
        stored = copy.deepcopy(built.to_stored_object())
        stored["request"]["messages"][0]["content"] = "changed"
        self.assertEqual(
            built.to_stored_object()["request"]["messages"][0]["content"],
            "hi",
        )


if __name__ == "__main__":
    unittest.main()
